### ISSUE TITLE
just need one identifier for session

### ISSUE THREAD

**Issue by strahe** [findmine/aiologin#8]
Hi， i define a class like 
```
class User(aiologin.AbstractUser):
    def __init__(self, email, password):
        print("user class made")
        self.email = email
        self.password = password
```
i found the session data like this:
```
{'created': 1484021019, 'session': {'__aiologin__': {'email': '1', 'password': '1'}}}
```
but if i pass some obj like:
```
class User(aiologin.AbstractUser):
    def __init__(self, db_obj):
        self.db = db_obj
```
I got an error.(obj can not be json.dumps).
I think it may be enough to just store an id in session.
I am sorry for my English，and thank you for this plugin.

**Comment by trivigy** [comment]
send over the consul stack trace. I want to see the entire message. I think the issue is in aiohttp_session. I think it's because the session encodes the data using json and your arbitrary object cannot be encoded.

**Comment by strahe** [comment]
@trivigy Hi, you are right, the aiohttp_session encodes the data using json, but i found  this in aiologin:
```
@asyncio.coroutine
    def login(self, user, remember):
        assert isinstance(user, AbstractUser), \
            "Expected {} but received {}".format(type(AbstractUser), type(user))
        assert isinstance(remember, bool), \
            "Expected {!r} but received {!r}".format(type(bool), type(remember))
        session = yield from self._session(self._request)
        try:
            session.remember = remember
        except:
            session['_remember'] = remember
        session[self._session_name] = dict(user)
        for coro in self._on_login:
            yield from coro(self._request)
```
The key is this line of code
`session[self._session_name] = dict(user)`
Actually， I do not think it's necessary to "dict(user)", maybe just `session[self._session_name] = user.id` is enough.
Thanks.

**Comment by trivigy** [comment]
The reason I pass a dict of user there is because user is a class type. The idea is to allow devs to just declare a AbstractUser derived class and set it's attributes which will then be extracted via the dict() process. Make sure to read `AbstractUser` and pay closer attention to __getitem__() and __setitem__(). That's part of the design of the library. I am not going to change that. If you can think of a way to write an additive functionality that adds the control of encoding while processing dict(user) feel free to write it up and PR. For my use case I don't need that kind of extended functionality.

workaround: 
```python
class CustomUser(AbstractUser):
    def __init__(self):
        self.variable = custom_encoder.dumps(<something>) 
```

This way you could serialize your variables before putting them onto the session. Remember that at the end of the day the limitation here is the storage. In this case I was using aiohttp simple cookie storage that uses strings to store data.

**Comment by strahe** [comment]
@trivigy well, i see, thanks.
