### ISSUE TITLE
[Question] how to use this project

### ISSUE THREAD

**Issue by centosuser** [findmine/aiologin#9]
I run the sample.py witch seems to run properly but I can't login. 
I try with curl and always get the response 405: Method Not Allowed. 
(and in the server console i get the 'unauthorized'). 
```
curl -v -c cookie.txt -d "email=user@sample.com" -d "password=blueberry" http://127.0.0.1:8080/login
curl -v -X GET --user user@sample.com --cookie-jar ./cookie.txt http://127.0.0.1:8080/login

```
Looking into the code (sample.py | line 121) I assume the proper method is the GET witch I use with curl
So what is the right way to login in the example code? Is it possible to write some working examples to login with curl or with a web form or anything else just to see a starting point of using this project?

**Comment by trivigy** [comment]
```
http://localhost:8080/login?email=user@sample.com&password=blueberry
```
in aiologin.setup() you have to pass special functions that you define. These are responsible for processing authorization via different methods. if you look at line 41, the way I define auth_by_form() is to actually process query parameters. The reason your curl doesn't work is because you are trying to send those parameters using encoded body data instead of query parameters. Either change how you submit the info in curl or change the auth_by_form() function to process form data rather than query parameters. That was the intention behind the library design. To give you, the dev, the control of how you want to process the authorization.

Just tested this and it works fine.
```bash
curl 'http://localhost:8080/login?email=user@sample.com&password=blueberry'
```
